### ISSUE TITLE
Run update

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/unfccc-detailed-data-by-party#1]
https://unfccc.int/process/transparency-and-reporting/greenhouse-gas-data/ghg-data-unfccc states

> In response to the mandate received from the SBSTA, the secretariat has made available the following six modules of the GHG data interface reflecting data reported by Annex I Parties and, to the extent possible, information provided in the national communications and biennial update reports of non-Annex I Parties as of 27 May 2018:

cc @AnnisG @AnnGuenther @mljeffery

**Comment by rgieseke** [comment]
See below for changes in date and countries covered in National Communications:

>  reported by Annex I Parties and, to the extent possible, information provided in the national communications and biennial update reports of non-Annex I Parties as of [-9 February-]{+27 May+} 2018

Note also the following footnotes from the data interface:
> Some non-Annex I Parties submitted their GHG inventory data using the format of the 2006 IPCC Guidelines in reporting GHG emissions/removals. For this reason, these data could not be included in the data interface. However, the data are available in the national communications [-(Antigua-]{+(Andorra, Antigua+} and Barbuda, Armenia, Brunei Darussalam, Côte d'Ivoire, Colombia, {+Eswatini,+} Ghana, Indonesia, Jamaica, Kiribati, Mauritania, {+Mongolia,+} Namibia, Republic of Moldova, Samoa, Serbia, {+Sierra Leone,+} Suriname, [-Swaziland-]{+United Arab Emirates+} and Venezuela) and biennial update reports (Andorra, Argentina, Armenia, Chile, Colombia, Costa Rica, Indonesia, Jordan, The Former Yugoslav Republic of Macedonia, Mauritania, Mongolia, Montenegro, Namibia, {+Nigeria,+} Serbia, South Africa, Togo, Tunisia and Uruguay).

**Comment by rgieseke** [comment]
@AnnisG Can you give this a test run and try to import it?

**Comment by AnnisG** [comment]
It's on my ToDo list for this week

**Comment by AnnisG** [comment]
non-AnnexI data imports fine now. AnnexI data comes in IPCC2006 categories and I have to create new specifications to make it work.

**Comment by rgieseke** [comment]
Done and released.
