### ISSUE TITLE
Changes in data

### ISSUE THREAD

**Issue by JGuetschow** [openclimatedata/unfccc-detailed-data-by-party#4]
Some changes I found compared to the version downloaded in summer 2017.

## The following countries have new or changed data:
* Bosnia and Herzegovina: new data for 2012 and 2014 for individual gases and for aggregate Kyoto gases complete new timeseries from 2001 to 2014. Data unchanged from 1990 to 2000
* Chile: 2010, Kyoto GHG, category 2 datapoint that seemed erroneus in the last version has been corrected.
* Dominican Republic: Data for Year 2010 has been added.
* Ecuador: Data for 2012 has been added. Historical data has been changed (some data points have been removed). 1994 emissions are much higher than emissions for subsequent years.
* Guinea-Bissau: Data for Year 2010 has been added.
* Israel: Data for 2014 and 2015 has been added. Historical time series have been updated slightly.
* Republic of Korea: Data for 2013 and 2014 has been added. Historical CH4 time series have been updated and amended.
* Saint Lucia: Data for 2005 and 2010 has been added. Year 200 data has been adjusted. 1995 emissions still very high compared to other years (originating from CH4, category 6 (waste)).
* Madagascar: Data for 2005 - 2010 has been added.
* Paraguay: Data for 2005,2012 has been added. 1994 data has been revised.
* Saudi Arabia: Data for 2012 has been added.
* Solomon islands: Data has been added for up to four years depending on gas and category. Only few data available for individual gases.
* Thailand: Data for Year 2014 has been added. For aggregate Kyoto GHG a complete  timeseries from 2000 to 2013 has been added.
* Viet Nam: Data for Year 2013 has been added.

Small changes in individual sectors might be missing as countries where only investigated in detail where changes we visible in CATM0EL Kyoto GHG data.

## General problems
* Belize: Aggregate Kyoto GHG CATM0EL data does not coincide with calculated sums for years 2003, 2006,and 2009. (not a change actually)

**Comment by rgieseke** [comment]
Awesome, could you add a CHANGELOG.md file with this information?

**Comment by JGuetschow** [comment]
I'm still checking the data and will add it once I don't find any additional things.

**Comment by rgieseke** [comment]
Great, in the long run we should automate this with some Python code :-)

**Comment by JGuetschow** [comment]
changelog added
