### ISSUE TITLE
Update with 31 August 2018 data

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/unfccc-detailed-data-by-party#6]
Has been updated ... 
https://unfccc.int/process/transparency-and-reporting/greenhouse-gas-data/ghg-data-unfccc

Will do an update run.

/cc @JGuetschow

**Comment by rgieseke** [comment]
Seems no updates that weren't already include in the Decembe re-run.

**Comment by rgieseke** [comment]
@JGuetschow I'll prepare a new release, ok?

**Comment by JGuetschow** [comment]
sure, thanks!

**Comment by rgieseke** [comment]
Tagged a release, before finishing this up for Zenodo archival, can you give this a look and maybe test run on your machine, @JGuetschow? 

If made a few changes to the code so would be good to have a second check.

**Comment by JGuetschow** [comment]
Tested everything and it all worked fine. I have quite a lot of changes in the Annex I file (e.g. numbers changed to letters in the category codes). similar for the non-Annex I file. But as the version in the repo is from June that's probably fine and just the changes you made, right?

**Comment by rgieseke** [comment]
Yes, there were only some changes two months ago in non-annex i data.

**Comment by rgieseke** [comment]
Done and on Zenodo: https://zenodo.org/record/2579952
